### PR TITLE
Adds a destroy mechanism

### PR DESCRIPTION
**Pull request by bennett000**
There's a lot of room for improvement in this PR.  This PR was motivated by a specific use case:

I have an application that needs to "unmount" or destroy Angular 2.  This application also preserves its Redux store outside of Angular 2.  Things have been going well but once routing was added I started to hit issues.

What would happen is that despite Angular 2 being torn down, Redux events were still triggering route changes but with the Angular 2 DOM gone and the components unmounted through their own `destroy` mechanisms having been used.  In other words, a memory leak.

I set out to see if there were any Redux store `subscribe` calls not being unregistered.  Turned out everything worked on Observables thanks the the mechanics of `BehaviourSubject`s.

I'm not completely convinced that I've solved my problem.  The PR I've filed here works in that in my project it actually stops the callbacks being fired, but I don't fully understand the root problem and that makes me uncomfortable.  There might be a deeper issue with respect to me not unloading ng2-redux itself.  I'm not really sure what that would entail though.  It uses `BehaviourSubject`s and they don't really seem to have a "teardown" mechanism.

### CODE REVIEW

**Comment by dagstuan** [comment]
Thanks for this! I didnt consider a use case like this where angular is torn down while redux is kept alive. So a `destroy()` method should be needed. I cleaned up your implementation a bit and pushed it to master. However, I'm still unsure about your destroy method where you had to call `complete()` on one of the subscriptions. Did you have issues with events still being fired?

**Comment by bennett000** [comment]
@dagstuan the `complete()` use was exactly that, there was an issue with events still firing.

My project is open source.  I haven't published yet but I will be soon.  If my application is still leaking after I upgrade ng2-redux-router I'll file a more complete PR and or GitHub issue that points directly to my code.

Thanks for the quick response.

**Comment by dagstuan** [comment]
@bennett000 okay, I published v1.1.0 to npm now. Let me know if you're still having issues after destroying ng2-redux-router :)

**Comment by bennett000** [comment]
@dagstuan everything is good on my end.  Thanks a lot for getting this fix out.

I think I must have confused myself with the `.complete` thing, it was late night side project stuff.  :)

**Pull request closed without merging**
